name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-release:
    name: Build & Release Apps
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Recreate Platform Folders
        working-directory: ./mubtadiaat_app
        run: |
          flutter create .
          git checkout -- web/

      - name: Install Dependencies
        working-directory: ./mubtadiaat_app
        run: flutter pub get

      - name: Build APK
        working-directory: ./mubtadiaat_app
        run: flutter build apk --release

      - name: Build AppBundle
        working-directory: ./mubtadiaat_app
        run: flutter build appbundle --release

      - name: Build Windows EXE
        working-directory: ./mubtadiaat_app
        run: flutter build windows --release

      - name: Install Inno Setup
        run: choco install innosetup

      - name: Compile Windows Installer
        working-directory: ./mubtadiaat_app/windows
        run: iscc installer.iss

      - name: Build Web
        working-directory: ./mubtadiaat_app
        run: flutter build web --release --base-href "/flutter-mubtadiaat/"

      - name: Upload Web Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./mubtadiaat_app/build/web

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./mubtadiaat_app/build/app/outputs/flutter-apk/app-release.apk
            ./mubtadiaat_app/build/app/outputs/bundle/release/app-release.aab
            ./mubtadiaat_app/build/windows/installer/Mubtadiaat_Setup.exe
          generate_release_notes: true

  deploy-pages:
    name: Deploy to GitHub Pages
    needs: build-and-release
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
